class Tag:
    def __init__(self,spaces,parentheses,content,condition,row,idnum):
        self.spaces=spaces  #空几格
        self.parentheses=parentheses  #左右括号
        self.content=content  #标签内容
        self.condition=condition  #条件
        self.row=row #第几行
        self.idnum=idnum
    def getSpaces(self):
        return self.spaces
    def getParentheses(self):
        return self.parentheses
    def getContent(self):
        return self.content
    def getCondition(self):
        return self.condition
    def getRow(self):
        return self.row
    def getId(self):
        return self.idnum